[package]
name = "minigit"
version = "0.1.0"
authors = ["Aurélien Gamet <a.gamet@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"
flate2 = "1.0"
chrono = "0.4"
rand = "0.6"
backtrace = "0.3"
